run_id: default

dirs:
  data: /home/teddy/local/data 
  extdata: /home/teddy/local/lincs-gsnn/extdata
  runs: /home/teddy/local/workflow_outputs/lincs-gsnn
  preds: /home/teddy/local/workflow_outputs/lincs-traj/runs/exp/default_v02/output/predict_grid
  bio_network: bionetwork  # dirs.runs/run_id/dirs.bio_network
  pretrain: pretrain  # dirs.runs/run_id/dirs.pretrain

scripts:
  make_bio_network:     scripts/make_bio_network.py
  pretrain:             scripts/pretrain_gsnn_with_dxdt.py
  explain:              scripts/explain.py

make_bio_network: 
  include_mirna:    '--include_mirna'
  include_extra:    '--include_extra'
  dorothea_levels:  'AB' 
  max_dti_kd:       1000.0
  filter_depth:     4
  
pretrain: 
  batch_size: 256
  num_workers: 20 
  epochs: 50
  lr: 1e-3
  wd: 0
  init: 'degree_normalized'
  patience: 5
  channels: 10
  layers: 6
  share_layers: '' #--share_layers
  dropout: 0
  norm: 'layer'
  checkpoint: '--checkpoint'
