import os, datetime
import yaml 

# ------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------


configfile: "config.yaml"
cfg = config

RUN_ID  = cfg["run_id"]

BIO_NET_DIR = os.path.join(cfg['dirs']['runs'], RUN_ID, cfg['dirs']["bio_network"])
PRETRAIN_DIR = os.path.join(cfg['dirs']['runs'], RUN_ID, cfg['dirs']["pretrain"])
EXPLAIN_DIR = os.path.join(cfg['dirs']['runs'], RUN_ID, 'explain')

os.makedirs(BIO_NET_DIR, exist_ok=True)
os.makedirs(PRETRAIN_DIR, exist_ok=True)
os.makedirs(EXPLAIN_DIR, exist_ok=True)


# ------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------
rule all:
    input:
        os.path.join(BIO_NET_DIR, f"bionetwork.pt"),
        os.path.join(PRETRAIN_DIR, f"pretrained_model.pt"),
# ------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------


rule make_bio_network:
    ''''''
    output:
        net = os.path.join(BIO_NET_DIR, f"bionetwork.pt")
    params:
        script = cfg['scripts']["make_bio_network"],
        data = cfg['dirs']["data"],
        extdata = cfg['dirs']["extdata"],
        meta = cfg['dirs']["preds"],
        out = BIO_NET_DIR,
        include_mirna = cfg['make_bio_network']["include_mirna"],
        include_extra = cfg['make_bio_network']["include_extra"],
        dorothea_levels = cfg['make_bio_network']["dorothea_levels"],
        max_dti_kd = cfg['make_bio_network']["max_dti_kd"],
        filter_depth = cfg['make_bio_network']["filter_depth"],

    shell:
        """
        python {params.script} \
            --data {params.data} \
            --out  {params.out} \
            --extdata {params.extdata} \
            --meta {params.meta} \
            {params.include_mirna} \
            {params.include_extra} \
            --dorothea_levels {params.dorothea_levels} \
            --max_dti_kd {params.max_dti_kd} \
            --filter_depth {params.filter_depth}
        """

rule pretrain_gsnn:
    input:
        bionet = BIO_NET_DIR,
        data = cfg['dirs']["preds"],
    output:
        model = os.path.join(PRETRAIN_DIR, f"pretrained_model.pt"),
    params:
        script = cfg['scripts']["pretrain"],
        data = cfg['dirs']['preds'],
        out = PRETRAIN_DIR,
        batch_size = cfg['pretrain']["batch_size"],
        num_workers = cfg['pretrain']["num_workers"],
        epochs = cfg['pretrain']["epochs"],
        lr = cfg['pretrain']["lr"],
        wd = cfg['pretrain']["wd"],
        init = cfg['pretrain']["init"],
        patience = cfg['pretrain']["patience"],
        channels = cfg['pretrain']["channels"],
        layers = cfg['pretrain']["layers"],
        share_layers = cfg['pretrain']["share_layers"],
        dropout = cfg['pretrain']["dropout"],
        norm = cfg['pretrain']["norm"],
        checkpoint = cfg['pretrain']["checkpoint"],

    shell:
        """
        python {params.script} \
            --data {params.data} \
            --out {params.out} \
            --bionet {input.bionet} \
            --batch_size {params.batch_size} \
            --num_workers {params.num_workers} \
            --epochs {params.epochs} \
            --lr {params.lr} \
            --wd {params.wd} \
            --init {params.init} \
            --patience {params.patience} \
            --channels {params.channels} \
            --layers {params.layers} \
            {params.share_layers} \
            --dropout {params.dropout} \
            --norm {params.norm} \
            {params.checkpoint}
        """
