name: lincs-gsnn

channels:
  - pytorch
  - pyg
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python
  - pandas
  - numpy
  - pytorch::pytorch
  - umap-learn
  - pyg::pyg
  - networkx
  - scikit-learn
  - scipy
  - snakemake
  - matplotlib
  - pysftp
  - seaborn
  - h5py
  - torchdiffeq
  - joblib
  - pip
  - pip:
      - pypath-omnipath
      - omnipath
      - ipykernel