import os, datetime
import yaml 
import glob

# ------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------


configfile: "config.yaml"
cfg = config

RUN_ID  = cfg["run_id"]

BIO_NET_DIR = os.path.join(cfg['dirs']['runs'], RUN_ID, cfg['dirs']["bio_network"])
PRETRAIN_DIR = os.path.join(cfg['dirs']['runs'], RUN_ID, cfg['dirs']["pretrain"])
EXPLAIN_DIR = os.path.join(cfg['dirs']['runs'], RUN_ID, 'explain')
INFER_EDGES_DIR = os.path.join(cfg['dirs']['runs'], RUN_ID, 'infer_edges')
EVAL_EDGES_DIR = os.path.join(cfg['dirs']['runs'], RUN_ID, 'inference_outputs')

os.makedirs(BIO_NET_DIR, exist_ok=True)
os.makedirs(PRETRAIN_DIR, exist_ok=True)
os.makedirs(EXPLAIN_DIR, exist_ok=True)
os.makedirs(INFER_EDGES_DIR, exist_ok=True)
os.makedirs(EVAL_EDGES_DIR, exist_ok=True)

# Find all sample directories
PREDS_DIR = cfg['dirs']["preds"]
SAMPLES = [os.path.basename(p) for p in glob.glob(os.path.join(PREDS_DIR, "sample_*")) if os.path.isdir(p)]
print(f"Found samples: {SAMPLES}")


# ------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------
rule all:
    input:
        os.path.join(BIO_NET_DIR, f"bionetwork.pt"),
        expand(os.path.join(PRETRAIN_DIR, "pretrained_model_{sample}.pt"), sample=SAMPLES),
        expand(os.path.join(INFER_EDGES_DIR, "{sample}", "inferred_output_edges_test.csv"), sample=SAMPLES),
        os.path.join(EVAL_EDGES_DIR, "evaluation_results.json"),
# ------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------


rule make_bio_network:
    ''''''
    output:
        net = os.path.join(BIO_NET_DIR, f"bionetwork.pt")
    params:
        script = cfg['scripts']["make_bio_network"],
        data = cfg['dirs']["data"],
        extdata = cfg['dirs']["extdata"],
        meta = cfg['dirs']["preds"],
        out = BIO_NET_DIR,
        include_mirna = cfg['make_bio_network']["include_mirna"],
        include_extra = cfg['make_bio_network']["include_extra"],
        dorothea_levels = cfg['make_bio_network']["dorothea_levels"],
        max_dti_kd = cfg['make_bio_network']["max_dti_kd"],
        filter_depth = cfg['make_bio_network']["filter_depth"],
        remove_output_edges = cfg['make_bio_network']["remove_output_edges"],
        n_edges_to_remove = cfg['make_bio_network']["n_edges_to_remove"],
        seed = cfg['make_bio_network']["seed"],

    shell:
        """
        python {params.script} \
            --data {params.data} \
            --out  {params.out} \
            --extdata {params.extdata} \
            --meta {params.meta} \
            {params.include_mirna} \
            {params.include_extra} \
            --dorothea_levels {params.dorothea_levels} \
            --max_dti_kd {params.max_dti_kd} \
            --filter_depth {params.filter_depth} \
            {params.remove_output_edges} \
            --n_edges_to_remove {params.n_edges_to_remove} \
            --seed {params.seed}
        """

rule pretrain_gsnn:
    input:
        bionet = os.path.join(BIO_NET_DIR, "bionetwork.pt"),
        sample_obs = os.path.join(cfg['dirs']["preds"], "{sample}", "obs"),
        sample_dxdt = os.path.join(cfg['dirs']["preds"], "{sample}", "dxdt"),
    output:
        model = os.path.join(PRETRAIN_DIR, "pretrained_model_{sample}.pt"),
        scale = os.path.join(PRETRAIN_DIR, "dxdt_scale_{sample}.pt"),
    params:
        script = cfg['scripts']["pretrain"],
        data = cfg['dirs']['preds'],
        out = PRETRAIN_DIR,
        batch_size = cfg['pretrain']["batch_size"],
        num_workers = cfg['pretrain']["num_workers"],
        epochs = cfg['pretrain']["epochs"],
        lr = cfg['pretrain']["lr"],
        wd = cfg['pretrain']["wd"],
        init = cfg['pretrain']["init"],
        patience = cfg['pretrain']["patience"],
        channels = cfg['pretrain']["channels"],
        layers = cfg['pretrain']["layers"],
        share_layers = cfg['pretrain']["share_layers"],
        dropout = cfg['pretrain']["dropout"],
        norm = cfg['pretrain']["norm"],
        checkpoint = cfg['pretrain']["checkpoint"],

    shell:
        """
        python {params.script} \
            --data {params.data} \
            --out {params.out} \
            --bionet $(dirname {input.bionet}) \
            --sample {wildcards.sample} \
            --batch_size {params.batch_size} \
            --num_workers {params.num_workers} \
            --epochs {params.epochs} \
            --lr {params.lr} \
            --wd {params.wd} \
            --init {params.init} \
            --patience {params.patience} \
            --channels {params.channels} \
            --layers {params.layers} \
            {params.share_layers} \
            --dropout {params.dropout} \
            --norm {params.norm} \
            {params.checkpoint}
        """

rule infer_output_edges:
    input:
        bionet = os.path.join(BIO_NET_DIR, "bionetwork.pt"),
        pretrained_model = os.path.join(PRETRAIN_DIR, "pretrained_model_{sample}.pt"),
        dxdt_scale = os.path.join(PRETRAIN_DIR, "dxdt_scale_{sample}.pt"),
        sample_obs = os.path.join(cfg['dirs']["preds"], "{sample}", "obs"),
        sample_dxdt = os.path.join(cfg['dirs']["preds"], "{sample}", "dxdt"),
    output:
        results = os.path.join(INFER_EDGES_DIR, "{sample}", "inferred_output_edges_test.csv"),
    params:
        script = cfg['scripts']["infer_output_edges"],
        preds_dir = cfg['dirs']["preds"],
        out_dir = os.path.join(INFER_EDGES_DIR, "{sample}"),
        batch_size = cfg['infer_output_edges']["batch_size"],
        train_prop = cfg['infer_output_edges']["train_prop"],
        lr = cfg['infer_output_edges']["lr"],
        wd = cfg['infer_output_edges']["wd"],
        epochs = cfg['infer_output_edges']["epochs"],
        agg = cfg['infer_output_edges']["agg"],
        use_batchnorm = cfg['infer_output_edges']["use_batchnorm"],
    shell:
        """
        mkdir -p {params.out_dir}
        python {params.script} \
            --gsnn_root {params.preds_dir} \
            --traj_root $(dirname {input.bionet}) \
            --dxdt_dir {input.sample_dxdt} \
            --out {params.out_dir} \
            --pretrained $(dirname {input.pretrained_model}) \
            --sample {wildcards.sample} \
            --batch_size {params.batch_size} \
            --train_prop {params.train_prop} \
            --lr {params.lr} \
            --wd {params.wd} \
            --epochs {params.epochs} \
            --agg {params.agg} \
            {params.use_batchnorm}
        """

rule eval_inferred_edges:
    input:
        bionet_dir = BIO_NET_DIR,
        inferred_edges = expand(os.path.join(INFER_EDGES_DIR, "{sample}", "inferred_output_edges_test.csv"), sample=SAMPLES),
    output:
        evaluation_results = os.path.join(EVAL_EDGES_DIR, "evaluation_results.json"),
        merged_edges = os.path.join(EVAL_EDGES_DIR, "merged_edges_evaluation.csv"),
    params:
        script = cfg['scripts']["eval_inferred_edges"],
        infer_edges_dir = INFER_EDGES_DIR,
        bio_network_dir = BIO_NET_DIR,
        out_dir = EVAL_EDGES_DIR,
        agg_method = cfg['eval_inferred_edges']["agg_method"],
        target_metric = cfg['eval_inferred_edges']["target_metric"],
    shell:
        """
        python {params.script} \
            --infer_edges_dir {params.infer_edges_dir} \
            --bio_network_dir {params.bio_network_dir} \
            --out_dir {params.out_dir} \
            --agg_method {params.agg_method} \
            --target_metric {params.target_metric}
        """
